### ISSUE TITLE
Pas de création de personnage à la connexion

### ISSUE THREAD

**Issue by TaylorDrift** [AnotherLifeRP/bugtracker#1]
Après avoir suivi la procédure, à ma première connexion sur le serveur (via launcher v1.1.2) la création de personnage n'est pas disponible et je suis invisible.

**Comment by ballzymilla** [comment]
Salut,

Tu as du te connecter pendant un restart serveur, essaye à nouveau.

**Comment by indilo53** [comment]
Bonjour, ton problème est-il résolu ?
