### ISSUE TITLE
Activation de la pointeuse

### ISSUE THREAD

**Issue by Tone93** [AnotherLifeRP/bugtracker#10]
Hello,
Pour la pointeuse du Bureau de Shérif de Paleto: 
 -Le point rouge au sol est bien visible.
 - Il s'affiche sur l'écran " Appuyer sur E pour pointer à votre travail "
=> En appuyant sur E, rien ne se passe. 
Ci-joint une capture d'écran avec la console F8.
![20190126021223_1](https://user-images.githubusercontent.com/47046575/51780649-75bc9f80-2110-11e9-8d4c-533a68eaa8ed.jpg)

Merci d'avance pour votre aide !

**Comment by Tone93** [comment]
Actualisation de la problématique : Je peux maintenant pour ma part prendre le service, une notification s'affiche en bas à droite.
Par contre les employés du Bureau ne voient pas le point rouge au sol, et ne peuvent donc pas activer leur pointage.

**Comment by ballzymilla** [comment]
Normalement elles sont ok depuis hier soir tard
