### ISSUE TITLE
Employé medical peut embaucher ou licencier

### ISSUE THREAD

**Issue by StigMakor** [AnotherLifeRP/bugtracker#13]
a l'hopital une fois que j'ai embauché quelqu'un cette personne peut embaucher ou licencier qui elle veut  ( dans la logique on le sait que seul le directeur a le droit )  mais on sait jamasi avec les trolls qu'on peut rencontrer . allez courage

**Comment by StigMakor** [comment]
Fermé sans faire expres

**Comment by Nico967** [comment]
Hello, idem pour mécano. Par contre j'ai essayé en tant que simple employé de recruter, et ça ne marche pas, c'est juste le visuel qui serait à retirer à priori :)

**Comment by indilo53** [comment]
Corrigé
