### ISSUE TITLE
Animation renvoie sur un nil vide

### ISSUE THREAD

**Issue by PitiShaCH** [AnotherLifeRP/bugtracker#14]
Bonjour,

Je viens de voir que les animations semble pointer sur aucune fonction. Elles fonctionnaient hier.
J'ai tenté un déco reco voir si le script ne s'était pas mal load en local.
La touche "3" est fonctionnelle, quand on choisi un menu d'animation,  tout les "nil" sont inaccessibles.

[
![image](https://user-images.githubusercontent.com/47068559/51793670-3485c780-21c4-11e9-9b86-cca8af626e01.png)
](url)

**Comment by ballzymilla** [comment]
On les a cut pour l'instant, on rework le système.
