### ISSUE TITLE
Vocal défectueux 

### ISSUE THREAD

**Issue by Nico967** [AnotherLifeRP/bugtracker#16]
Nous sommes 4 à Sandy shore devant le garage, à ne pas avoir de vocal du tout, malgré les 3/4 tentatives de déconnexion & Activer/désactiver le vocal IG.

**Comment by Nico967** [comment]
C'est aléatoire mais en général quand il y a un changement de comté ou une déco reco 2 fois sur 3 le son à un problème dans un sens ou dans les deux (soit les autre nous entendent mais nous on les entend pas soit l'inverse soit rien du tout)

**Comment by ballzymilla** [comment]
On est en train de check
