### ISSUE TITLE
Soucis d'accès au coffre

### ISSUE THREAD

**Issue by Zack594** [AnotherLifeRP/bugtracker#18]
Plus d'accès au coffre sur le serveur DownTown uniquement sur celui la, avant aucun soucis et depuis hier soir le soucis est apparue.

Image prise au moment du soucis:

https://prnt.sc/mcybv5

**Comment by ballzymilla** [comment]
Quand cela t'arrive déplace un peu ta voiture et attend un peu, c'est surement le temps que le véhicule sauvegarde sa dernière position.

**Comment by Skiletz** [comment]
https://plays.tv/video/5c51a7e2f1ff8f2a7e/bug-coffre

Ça refonctionne après 2 déco reco
