### ISSUE TITLE
Sirène véhicule dépanneur

### ISSUE THREAD

**Issue by Skiletz** [AnotherLifeRP/bugtracker#19]
Quand le véhicule dépanneur active ses gyrophares, aucune sirène ne s'entend si on se tient à proximité. Par contre une fois que le véhicule s'éloigne on entend la sirène.

**Comment by ballzymilla** [comment]
Il n'y a pas de sirène, juste les gyrophares visuels normalement.

**Comment by Skiletz** [comment]
En effet mais une fois que le véhicule quitte un certain périmètre autour du joueur, la sirène se fait entendre

**Comment by ballzymilla** [comment]
FiveM qui gère ça, pas nous :p
