### ISSUE TITLE
Menu interaction

### ISSUE THREAD

**Issue by balrockze** [AnotherLifeRP/bugtracker#25]
mon menu interaction objet marcher pas depuis 3jour quand je clique sur un objet j'ai une grosse chute de fps et le menu s'ouvre pas

**Comment by ballzymilla** [comment]
Des interactions admins fuck le système.

**Comment by Eshanie** [comment]
Pareil pour moi depuis aujourd'hui (30/01/19) je n'ai plus accès aux menus interactions. Impossible de s'assoir / Verouiller des portes / etc
