### ISSUE TITLE
Pointages des employés d'entreprise

### ISSUE THREAD

**Issue by PitiShaCH** [AnotherLifeRP/bugtracker#26]
monolinkAujourd'hui à 20:09
les gerants d'entreprise vous avez reussis a voir les heures de vous employés pour ma parts même s'ils son fait plus d'une heure de travail cela affiche zero  ?`

Il semble que malgré l'attente d'une heure demandée, le pointage est toujours à zéro.
Il y a-t-il des retours de différents gérants d'entreprise ?

**Comment by ballzymilla** [comment]
Quelle entreprise et le prénom / nom rp du patron/employé svp ?
