### ISSUE TITLE
Caméra bloqué (container)

### ISSUE THREAD

**Issue by Nico967** [AnotherLifeRP/bugtracker#28]
Suite à l'utilisation d'une armoire société, la caméra reste bloqué en vue de dessus, pendant que notre personnage peut encore se déplacer

SCREEN: https://cdn.discordapp.com/attachments/503590763624529921/539935079418429461/unknown.png

**Comment by ballzymilla** [comment]
tu appuie sur "1" interaction pour débloquer :)
