### ISSUE TITLE
Problème de reco - véhicule  glitché dans un bâtiment 

### ISSUE THREAD

**Issue by GamerKillerTV** [AnotherLifeRP/bugtracker#3]
![image](https://user-images.githubusercontent.com/47007424/51698768-13ad4e80-1fd9-11e9-8cd9-9b3ac461fb28.png)

**Comment by ballzymilla** [comment]
As-tu récupéré ton véhicule ?

**Comment by GamerKillerTV** [comment]
> As-tu récupéré ton véhicule ?

Non, toujours pas. (Désolé pour le temps de réponse, je suis FR mais j'habite au Québec)

**Comment by indilo53** [comment]
Bonjour, peux-tu me donner ta plaque ?

**Comment by GamerKillerTV** [comment]
> Bonjour, peux-tu me donner ta plaque ?

24LXJ747
