### ISSUE TITLE
Sifflement et ecran noir en voiture en tant que passager

### ISSUE THREAD

**Issue by pedzakbyker** [AnotherLifeRP/bugtracker#30]
j'aimerais savoir si c'est soit un bug asser recurant, soit l'applicatin de la medecine poussee du serveur?
Car en tant que auto ecole  je suis passager, et a chaques fois en passager j'ai l'ecran noir et des sifflements pour rien!
On ne roule meme pas vite, je ne comprends pas d'ou ca peut provenir.
Seul en voiture aucun soucis, des que j'ai un eleve pour l'auto ecole j'ai un "risque" d'avoir le sifflement et ecran noir :/

**Comment by watsy17** [comment]
En cours de correction
