### ISSUE TITLE
Téléphone portable

### ISSUE THREAD

**Issue by Nico967** [AnotherLifeRP/bugtracker#33]
Il y a beaucoup de délais entre chaque "sauvegarde" du téléphone. Si l'on ferme son tel après avoir enregistré un contact, il s'actualisera et apparaîtra seulement une bonne heure après (pour avoir essayé ce soir). Pareil pour n'importe quel info qu'il y a dessus, que ce soit SMS ou appels.

**Comment by indilo53** [comment]
Corrigé, c'était seuelement visuel il sauvegardait instant
