### ISSUE TITLE
Doublon de véhicule 

### ISSUE THREAD

**Issue by aNt3r4** [AnotherLifeRP/bugtracker#38]
Ce matin j'ai constater un regroupement de véhicule au même endroit 
Garage SandyShore (Déplacement des véhicules en RP le temps que vous vous en occupiez) 
Plaque des véhicules originels: 
09QR0771
01PSY514
83TJV039
40IVI164
![20190204105149_1](https://user-images.githubusercontent.com/47056236/52201278-4ffb6d00-286b-11e9-8a41-12d935f6b678.jpg)
![20190204105229_1](https://user-images.githubusercontent.com/47056236/52201284-525dc700-286b-11e9-9fca-cbabe1d52405.jpg)

**Comment by indilo53** [comment]
Corrigé
