### ISSUE TITLE
Bug Interaction 1 

### ISSUE THREAD

**Issue by Nico967** [AnotherLifeRP/bugtracker#6]
Salut, lorsque je fais "1", puis clique droit, le menu habituel ne s'affiche pas, au lieu de ça j'ai un petit freeze + le resource time warning de fiveM. Je ne sais pas du tout si je suis le seul à l'avoir ou non. J'ai ça depuis le 25 aux alentours de 1h ~ 2h.

Screen: https://image.noelshack.com/fichiers/2019/04/5/1548412420-unknown2.png

**Comment by ballzymilla** [comment]
Ca devrait être ok, tiens nous au jus

**Comment by Nico967** [comment]
Non toujours pas malheureusement.
https://image.noelshack.com/fichiers/2019/04/5/1548420606-unknown2.png

**Comment by ballzymilla** [comment]
@indilo53 Si tu peux check ça va au-dela de mes compétences ;)

**Comment by Nico967** [comment]
Je viens d'essayer à nouveau, et ça à l'air de remarcher !
