### ISSUE TITLE
Ma voiture a disparu

### ISSUE THREAD

**Issue by pedzakbyker** [AnotherLifeRP/bugtracker#7]
A ma reconnection aujourd'hui, ma voiture n'etait plus la ou je l'avais garee.
Je ne sais pas si elle est dans un autre serveur car je suis sur et certain de m'etre bien deconnecte sur Dell Perro.

**Comment by pedzakbyker** [comment]
Bon baaaah autant pour moi elle etait a down town a l'endroit ou j'ai fait le cross serveur et ca faisait que 10m meme pas --'
Desole du derangement, je ne sais pas comment supprimer le ticket

**Comment by ballzymilla** [comment]
Je m'en occupe pas de soucis ;)
