### ISSUE TITLE
Probléme de creation de carte d'identité 

### ISSUE THREAD

**Issue by TontonGeek** [AnotherLifeRP/bugtracker#9]
Bonsoir , 

Je viens d'arrivé en ville aujourd'hui mème et je rencontre un petit soucis à la création de ma carte d'identité avec le maire . 
En gros il prend ma photo et crée normalement et simplement la carte mais mon nom de famille ne veut pas s'afficher sur ma carte imprimé . 

Mon nom est Danny McCoy 
https://cdn.discordapp.com/attachments/350053585964236801/538489098957225984/image0.jpg
Si vous seriez m'aider cela serais formidable . 

Bien à vous Danny McCoy

**Comment by indilo53** [comment]
Bonjour, il y avait un espace en trop dans ton nom ca devrait etre résolu
